### ISSUE TITLE
I made a translation into Portuguese from Brazil

### ISSUE THREAD

**Issue by Havokdan** [luadch/translations#1]
I made a translation into Portuguese from Brazil. Não sei como colocar aqui, mas vou deixar o link como anexo dessa mensagem caso deseje. Inside the folder, in the "lang" folder is the main translation, the script is in "scripts / lang", all of the latest versions that I found on this date, I hope it is useful.

**Comment by Sopor** [comment]
There is now way to verify that this is working. And what do you mean that you translated `into Portuguese from Brazil`?

All translations should be made att Transifex...

**Comment by Havokdan** [comment]
Well, I tested it and it's working and I did not know the project was on Transifex, I'm sorry. I translated into Portuguese from Brazil, which is different from that of Portugal for example

**Comment by Sopor** [comment]
Yes, but you have added external scripts into the pack. This is for Luadch ONLY. And for Portuguese from Brazil it should be `pt_br`. `br` is Breton, not Brazil.

**Comment by Havokdan** [comment]
I was in doubt if it had two letter limit or not, so I put br, be afraid to use "_" or "-" and add more letters. Well, thank you, sorry for the inconvenience.

**Comment by Sopor** [comment]
Yes, it seems that there is a limit of two letters. Maybe it is time to change that?
You have also forgot to include a few lang files. This is why it should be done on Transifex.

**Comment by Sopor** [comment]
It seems to be quite easy to upload your files to Transifex, so maybe you could join us there and it will be easier for you to see what you didn't translated? Maybe you forgot them or you believed it wasn't necessary?

**Comment by Havokdan** [comment]
Okay, I'll make the request, I'll translate other things right there.

**Comment by blasti** [comment]
> Yes, it seems that there is a limit of two letters. Maybe it is time to change that?

There is no limit. You can savely use "pt_br" everywhere instead of "br".

**Comment by Sopor-** [comment]
> Yes, it seems that there is a limit of two letters.

Wrong, it should work with pt_br. I will try again :)

**Comment by Sopor** [comment]
Yes, it seems to work., but now i don't understand a thing on the hub menu so i will change it back :)

**Comment by Sopor** [comment]
@Havokdan I removed the Luadch_v2.19_br_language_pack.zip because i found a few errors in it. Some files are missing, some words you haven't translated (I don't know why?) and i found some missing double quotes that are really important. So please check your translation before you review them on Transifex.

**Comment by Sopor** [comment]
You will now find it [here](https://github.com/luadch/translations/tree/master/language_pack/pt-br) :)

**Comment by Havokdan** [comment]
> @Havokdan I removed the Luadch_v2.19_br_language_pack.zip because i found a few errors in it. Some files are missing, some words you haven't translated (I don't know why?) and i found some missing double quotes that are really important. So please check your translation before you review them on Transifex.

It's just that I'm not a computer scientist, I'm a hobbyist, I may have let something escape because I did not have confidence if I could translate, or it just happened without my noticing. Looking at Transifex, I realized I had several things I could have translated, but that was over.

> You will now find it here :)

Thanks, does this include script translations?
